---
title: "wk4 homework"
output: html_document
date: "2025-10-27"
---
```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)
library(tmap)
```
#读取数据
```{r}
GII <- read_csv(here::here("HDR25_Composite_indices_complete_time_series.csv"),
                       locale = locale(encoding = "latin1"),
                       na = " ", skip=0)

World <- st_read(here::here("World_Countries_(Generalized)_-573431906301700955/World_Countries_Generalized.shp"))
```
#清理数据
```{r}
GII_clean <- GII %>%
  clean_names() %>%
  select(iso3, country, gii_2010, gii_2019) %>%
  mutate(
    difference = gii_2019 - gii_2010,
    iso2 = countrycode(iso3, origin = "iso3c", destination = "iso2c")
  )

```
#数据加入
```{r}
world_joined <- left_join(World, GII_clean, by = c("ISO" = "iso2")) 
```
#检查数据
```{r}
glimpse(world_joined)
```
#可视化
```{r}
library(ggplot2)

ggplot(world_joined) +
  geom_sf(aes(fill = difference), color = "white", size = 0.1) +
  scale_fill_viridis_c(option = "plasma", na.value = "grey90") +
  theme_minimal() +
  labs(title = "Change in Gender Inequality Index (2010–2019)",
       fill = "Δ GII")
```


## New map
```{r}
tmap_mode("plot")

tm1 <- tm_shape(world_joined) +
  tm_polygons(
    col = "difference",
    palette = "BuPu",
    n = 5,
    style = "jenks",
    border.col = "black",
    border.lwd = 0.5,
    colorNA = "lightgrey",  # <--- show NA countries in gray
    title = "GII Difference (2019 - 2010)"
  )

tm1
```
```{r}
tm2 <- tm1 +
  tm_compass(type = "arrow",
             size = 1.8,
             position = tm_pos_in("left", "top"))

tm2
```

